In [1]:
import pandas as pd

In [2]:
emp=pd.read_excel(r"C:\Users\Shaik Mahimood\OneDrive\Documents\Downloads\excel 2.xlsx")

In [3]:
emp

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE,Purchase
0,XYZ,M,100,NaN,NaN,NaN,NaN,NaN,NaN,Z,W,B,NaN,NaN,100M,Y
1,BZC,F,200,IY,N,N,NaN,Y,N,Y,NaN,NaN,NaN,56.0,200M,N
2,ASDF,M,300,NaN,Y,Y,Y,NaN,200,NaN,NaN,NaN,6.0,70.0,300,y

In [4]:
emp.shape

(3, 16)

In [5]:
emp.columns

Index(['NAME', 'GENDER', 'SFT', 'OFFICE', 'SHOPING ', 'SCHOOLS', 'METROS',
       'PLAYGROUP', 'SALARY', 'HOME ', 'SKIN', 'HAIR', 'HEIGHT', 'WEIGHT',
       'PRICE', 'Purchase '],
      dtype='object')

In [6]:
emp.isnull()

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE,Purchase
0,False,False,False,True,True,True,True,True,True,False,False,False,True,True,False,False
1,False,False,False,False,False,False,True,False,False,False,True,True,True,False,False,False
2,False,False,False,True,False,False,False,True,False,True,True,True,False,False,False,False

In [152]:
emp.isnull().sum()

NAME         0
GENDER       0
SFT          0
OFFICE       2
SHOPING      1
SCHOOLS      1
METROS       2
PLAYGROUP    2
SALARY       1
HOME         1
SKIN         2
HAIR         2
HEIGHT       2
WEIGHT       1
PRICE        0
Purchase     0
dtype: int64

In [153]:
emp['OFFICE']

0    NaN
1     IY
2    NaN
Name: OFFICE, dtype: object

In [154]:
emp['SCHOOLS']

0    NaN
1      N
2      Y
Name: SCHOOLS, dtype: object

In [155]:
clean_data=emp.copy()

In [156]:
clean_data

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE,Purchase
0,XYZ,M,100,NaN,NaN,NaN,NaN,NaN,NaN,Z,W,B,NaN,NaN,100M,Y
1,BZC,F,200,IY,N,N,NaN,Y,N,Y,NaN,NaN,NaN,56.0,200M,N
2,ASDF,M,300,NaN,Y,Y,Y,NaN,200,NaN,NaN,NaN,6.0,70.0,300,y

In [157]:
import numpy as np

In [158]:
clean_data['OFFICE']=clean_data['OFFICE'].fillna(clean_data['OFFICE'].mode()[0])

In [159]:
clean_data['OFFICE']

0    IY
1    IY
2    IY
Name: OFFICE, dtype: object

In [160]:
clean_data['SCHOOLS']=clean_data['SCHOOLS'].fillna(clean_data['SCHOOLS'].mode()[0])

In [161]:
clean_data['SCHOOLS']

0    N
1    N
2    Y
Name: SCHOOLS, dtype: object

In [162]:
clean_data['PLAYGROUP']=clean_data['PLAYGROUP'].fillna(clean_data['PLAYGROUP'].mode()[0])

In [163]:
clean_data['PLAYGROUP']

0    Y
1    Y
2    Y
Name: PLAYGROUP, dtype: object

In [164]:
clean_data['OFFICE']=clean_data['OFFICE'].fillna(clean_data['OFFICE'].mode()[0])

In [165]:
clean_data['OFFICE']

0    IY
1    IY
2    IY
Name: OFFICE, dtype: object

In [166]:
clean_data['SCHOOLS']=clean_data['SCHOOLS'].fillna(clean_data['SCHOOLS'].mode()[0])

In [167]:
clean_data['SCHOOLS']

0    N
1    N
2    Y
Name: SCHOOLS, dtype: object

In [172]:
clean_data['SHOPING']=clean_data['SHOPING'].fillna(clean_data['SHOPING'].mode()[0])

In [173]:
clean_data['SHOPING']

0    N
1    N
2    Y
Name: SHOPING, dtype: object

In [174]:
clean_data.columns = clean_data.columns.str.strip()

In [175]:
clean_data.columns

Index(['NAME', 'GENDER', 'SFT', 'OFFICE', 'SHOPING', 'SCHOOLS', 'METROS',
       'PLAYGROUP', 'SALARY', 'HOME', 'SKIN', 'HAIR', 'HEIGHT', 'WEIGHT',
       'PRICE', 'Purchase'],
      dtype='object')

In [176]:
clean_data['SFT']=clean_data['SFT'].fillna(clean_data['SFT'].mode()[0])

In [177]:
clean_data['SFT']

0    100
1    200
2    300
Name: SFT, dtype: int64

In [178]:
clean_data['HOME']=clean_data['HOME'].fillna(clean_data['HOME'].mode()[0])

In [179]:
clean_data['HOME']

0    Z
1    Y
2    Y
Name: HOME, dtype: object

In [180]:
clean_data['SKIN']=clean_data['SKIN'].fillna(clean_data['SKIN'].mode()[0])

In [181]:
clean_data['SKIN']

0    W
1    W
2    W
Name: SKIN, dtype: object

In [182]:
clean_data['WEIGHT']=clean_data['WEIGHT'].fillna(clean_data['WEIGHT'].mode()[0])

In [183]:
clean_data['WEIGHT']

0    56.0
1    56.0
2    70.0
Name: WEIGHT, dtype: float64

In [184]:
clean_data['HEIGHT']=clean_data['HEIGHT'].fillna(clean_data['HEIGHT'].mode()[0])

In [185]:
clean_data['HEIGHT']

0    6.0
1    6.0
2    6.0
Name: HEIGHT, dtype: float64

In [186]:
clean_data

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE,Purchase
0,XYZ,M,100,IY,N,N,NaN,Y,NaN,Z,W,B,6.0,56.0,100M,Y
1,BZC,F,200,IY,N,N,NaN,Y,N,Y,W,NaN,6.0,56.0,200M,N
2,ASDF,M,300,IY,Y,Y,Y,Y,200,Y,W,NaN,6.0,70.0,300,y

In [187]:
clean_data['SALARY']=clean_data['SALARY'].fillna(clean_data['SALARY'].mode()[0])

C:\Users\Shaik Mahimood\AppData\Local\Temp\ipykernel_14372\2270182905.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'int' and 'str'
  clean_data['SALARY']=clean_data['SALARY'].fillna(clean_data['SALARY'].mode()[0])

In [188]:
clean_data['SALARY']

0      N
1      N
2    200
Name: SALARY, dtype: object

In [189]:
clean_data['HAIR']=clean_data['HAIR'].fillna(clean_data['HAIR'].mode()[0])

In [190]:
clean_data['HAIR']

0    B
1    B
2    B
Name: HAIR, dtype: object

In [191]:
clean_data['METROS']=clean_data['METROS'].fillna(clean_data['METROS'].mode()[0])

In [192]:
clean_data['METROS']

0    Y
1    Y
2    Y
Name: METROS, dtype: object

In [193]:
clean_data['Purchase']=clean_data['Purchase'].fillna(clean_data['Purchase'].mode()[0])

In [194]:
clean_data['Purchase']

0    Y
1    N
2    y
Name: Purchase, dtype: object

In [195]:
clean_data['WEIGHT']=clean_data['WEIGHT'].fillna(np.mean(pd.to_numeric(clean_data['WEIGHT'])))

In [196]:
clean_data['WEIGHT']

0    56.0
1    56.0
2    70.0
Name: WEIGHT, dtype: float64

In [197]:
clean_data

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE,Purchase
0,XYZ,M,100,IY,N,N,Y,Y,N,Z,W,B,6.0,56.0,100M,Y
1,BZC,F,200,IY,N,N,Y,Y,N,Y,W,B,6.0,56.0,200M,N
2,ASDF,M,300,IY,Y,Y,Y,Y,200,Y,W,B,6.0,70.0,300,y

In [198]:
clean_data.isnull()

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE,Purchase
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [200]:
clean_data.isnull().sum()

NAME         0
GENDER       0
SFT          0
OFFICE       0
SHOPING      0
SCHOOLS      0
METROS       0
PLAYGROUP    0
SALARY       0
HOME         0
SKIN         0
HAIR         0
HEIGHT       0
WEIGHT       0
PRICE        0
Purchase     0
dtype: int64

In [207]:
X_iv=clean_data[['NAME', 'GENDER', 'SFT', 'OFFICE', 'SHOPING', 'SCHOOLS', 'METROS',
       'PLAYGROUP', 'SALARY', 'HOME', 'SKIN', 'HAIR', 'HEIGHT', 'WEIGHT',
       'PRICE']]

In [208]:
X_iv

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE
0,XYZ,M,100,IY,N,N,Y,Y,N,Z,W,B,6.0,56.0,100M
1,BZC,F,200,IY,N,N,Y,Y,N,Y,W,B,6.0,56.0,200M
2,ASDF,M,300,IY,Y,Y,Y,Y,200,Y,W,B,6.0,70.0,300

In [209]:
y_dv=clean_data[['Purchase']]

In [210]:
y_dv

  Purchase
0        Y
1        N
2        y

In [211]:
imputation=pd.get_dummies(clean_data)

In [212]:
imputation

,SFT,HEIGHT,WEIGHT,NAME_ASDF,NAME_BZC,NAME_XYZ,GENDER_F,GENDER_M,OFFICE_IY,SHOPING_N,...,HOME_Y,HOME_Z,SKIN_W,HAIR_B,PRICE_300,PRICE_100M,PRICE_200M,Purchase_N,Purchase_Y,Purchase_y
0,100,6.0,56.0,False,False,True,False,True,True,True,...,False,True,True,True,False,True,False,False,True,False
1,200,6.0,56.0,False,True,False,True,False,True,True,...,True,False,True,True,False,False,True,True,False,False
2,300,6.0,70.0,True,False,False,False,True,True,False,...,True,False,True,True,True,False,False,False,False,True

In [213]:
clean_data

,NAME,GENDER,SFT,OFFICE,SHOPING,SCHOOLS,METROS,PLAYGROUP,SALARY,HOME,SKIN,HAIR,HEIGHT,WEIGHT,PRICE,Purchase
0,XYZ,M,100,IY,N,N,Y,Y,N,Z,W,B,6.0,56.0,100M,Y
1,BZC,F,200,IY,N,N,Y,Y,N,Y,W,B,6.0,56.0,200M,N
2,ASDF,M,300,IY,Y,Y,Y,Y,200,Y,W,B,6.0,70.0,300,y